//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_Application_Database.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z:\\Development\\C#\\Job Application Database\\Job Application Database\\jdb.json")]
        public string LastLoadedFile {
            get {
                return ((string)(this["LastLoadedFile"]));
            }
            set {
                this["LastLoadedFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoLoadLastFile {
            get {
                return ((bool)(this["AutoLoadLastFile"]));
            }
            set {
                this["AutoLoadLastFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string JobTitles {
            get {
                return ((string)(this["JobTitles"]));
            }
            set {
                this["JobTitles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoSave {
            get {
                return ((bool)(this["AutoSave"]));
            }
            set {
                this["AutoSave"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("./job.titles")]
        public string JobSaveFile {
            get {
                return ((string)(this["JobSaveFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{\""Name\"":\""(?<name>[a-zA-Z\\.,\\+ ]+)?\"",\""Web\"":\""(?<website>.*)?\"",\""Rep\"":(?<repid>[0-9]+)?,\""Job\"":(?<jobid>[0-9]+)?,\""Board\"":(?<boardid>[0-9]+)?,\""Position\"":(?<position>[0-9]+)?,\""Status\"":(?<status>[0-9]+)?,\""AppDate\"":\""(?<date>[0-9]+-[0-9]+-[0-9]+)?T00:00:00(-07:00)?\"",\""Location\"":\""(?<location>[a-zA-Z ,]+)?\"",\""Notes\"":\""(?<notes>.*)?\""}")]
        public string CompanyLoadRegex {
            get {
                return ((string)(this["CompanyLoadRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("./rep.titles")]
        public string RepSaveFile {
            get {
                return ((string)(this["RepSaveFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("./job.board")]
        public string BoardSaveFile {
            get {
                return ((string)(this["BoardSaveFile"]));
            }
        }
    }
}
